### ISSUE TITLE
android gradle plugin 升级 4.2.0 之后 sdk-editor-plugin 失效

### ISSUE THREAD

**Issue by Arowa-Z** [iwhys/sdk-editor-plugin#5]

**Comment by iwhys** [comment]
请使用最新版本[v1.1.6](https://jitpack.io/#iwhys/sdk-editor-plugin)
改版本适配了android gradle plugin 4.2.x
原有@ReplaceClass("包标识")，中的"包标识"改为依赖库格式[group:name:version]取[name:version]作为标识，如：原依赖[androidx.core:core:1.3.0] 取[core:1.3.0]作为标识
